.. _docref_common_ps_srv:

* Support Workflows for setting up and managing Puttshack Locations
* Event and Party management
* Gaming Slots management
* Music, food and drinks service bookings and reservation management
* Inventory management
* Workflows for enrolling players and managing their scores, statistics
* Notification of online product promotions
* Gift Cards dispensing and management
* Customer Perks management
* Secure Payments and cancellation management.
