.. _docref_common_cust_act:

* Browse a list of available Puttshack services,
* Identify locations where the services are offered,
* Make bookings as per customer preferences,
* Receive confirmation for customer bookings and hold reservations,
* Edit or cancel a reservation,
* Enroll into perks program,
* Make secure online payments,
* Purchase and redeem gift cards,
* Utilize perks which might include discounts on payments,
* Check game scores.
