# This is a basic workflow to help you get started with Actions

name: CI-linuxos

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  linux_build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
            apt-get update -y && apt-get install -y build-essential make libenchant-dev enchant git latexmk texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-luatex texlive-xetex dialog apt-utils && apt-get autoremove && apt-get clean && cp -rfv beta/docs/resources/fonts /usr/share/fonts && fc-cache -f -v
            python3 -m pip install --upgrade pip
            python3 -m pip install sphinx sphinx_rtd_theme
            python3 -m pip install -r docs/requirements.txt
      - name: Sphinx based descriptive Puttshack html docs build
        run: |
            val=`ls -alth`
            echo This is current dir contents $val
            make -C docs/ clean spelling html
