# This is a basic workflow to help you get started with Actions

name: CI-macos

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  macos_build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
          brew update
          brew install enchant
          brew install mermaid-cli
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme
          pip install -r docs/requirements.txt
    - name: Sphinx based descriptive Puttshack html docs build
      run: |
          val=`ls -alth`
          echo This is current dir contents $val
          make -C docs/ clean spelling html 
