.. _docref_common_ps_srv:

* See available times at a particular location.
* Plan an event or a party 
* Book gaming slots
* Manage players

  - Add or update player profiles
  - Enroll players for a booking,
  - Track player scores (*Future*)

* Promotions and notifications for Puttshack services
* Purchase and use gift cards
* Avail customer perks
* Seamless & secure online payments and cancellations.
* Avail music, food and drinks services (*Future*)

.. include:: /common/ps_future_note.inc
