.. _docref_common_thirdp:

+-------------------+-----------------+------------------+
|  Third Party Tool |     Purpose     |  Functionality   |
+===================+=================+==================+
| `Tripleseat`_     | |tripleseat_p|  | |tripleseat_f|   |
+-------------------+-----------------+------------------+
| `Punch`_          | |punch_p|       | |punch_f|        |
+-------------------+-----------------+------------------+
| `Stripe`_         | |stripe_p|      | |stripe_f|       |
+-------------------+-----------------+------------------+
| `Twilio`_         | |twilio_p|      | |twilio_f|       |
+-------------------+-----------------+------------------+
| `Sendgrid`_       | |sendgrid_p|    | |sendgrid_f|     |
+-------------------+-----------------+------------------+
| `FocusPOS`_       | |focuspos_p|    | |focuspos_f|     |
+-------------------+-----------------+------------------+
| `TevalisPOS`_     | |tevalis_p|     | |tevalis_f|      |
+-------------------+-----------------+------------------+
| `GiftPro`_        | |giftpro_p|     | |giftpro_f|      |
+-------------------+-----------------+------------------+
| `FocusGift`_      | |focusgift_p|   | |focusgift_p|    |
+-------------------+-----------------+------------------+

.. note::

     For details regarding each of these third party API providers that are utilized in Puttshack Cloud API implementation, see :ref:`Third Party API Provider Details<docref_puttshack_thirp_details>` section.

.. _Tripleseat: https://support.tripleseat.com/hc/en-us/sections/200821727-Tripleseat-API
.. |tripleseat_p| replace:: Event Management 
.. |tripleseat_f| replace:: Locations, Bookings, Leads
.. _Punch: https://punchh.com/platform/
.. |punch_p| replace:: Loyalty & Engagement
.. |punch_f| replace:: Perks, Enrollment, Redemption
.. _Stripe: https://stripe.com/docs/api
.. |stripe_p| replace:: Online Payments
.. |stripe_f| replace:: Payments
.. _Twilio: https://www.twilio.com/docs/usage/api
.. |twilio_p| replace:: Communications
.. |twilio_f| replace:: Text Messaging
.. _Sendgrid: https://sendgrid.com/solutions/email-api/ 
.. |sendgrid_p| replace:: Communications
.. |sendgrid_f| replace:: Emails, Promotions, Notifications
.. _FocusPOS: https://www.focuspos.com
.. |focuspos_p| replace:: Point of Sales
.. |focuspos_f| replace:: Mobile, Self-Service Kiosk
.. _TevalisPOS: https://website.tevalis.com/point-of-sale/
.. |tevalis_p| replace:: Point of Sales
.. |tevalis_f| replace:: Mobile, Self-Service Kiosk
.. _GiftPro:  https://www.giftpro.co.uk
.. |giftpro_p| replace:: Gifts
.. |giftpro_f| replace:: Vouchers & Gift Cards
.. _FocusGift: https://www.focuspos.com/myfocus/gift-card-program/
.. |focusgift_p| replace:: Gifts
.. |focusgift_f| replace:: Vouchers & Gift Cards
